DROP TABLE IF EXISTS bookings;

CREATE TABLE Bookings(
    Booking_id INT AUTO_INCREMENT PRIMARY KEY,
    User_id INT NOT NULL,
    Property_id INT NOT NULL,
    start_date DATE NOT NULL,
    End_date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT
    CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES properties(ptoperty_id))
    

    PARTITION BY RANGE (YEAR(start_date))(
        PARTITION p2023 VALUES LESS THAN (2024),
        PARTITION p2024 VALUES LESS THAN (2025),
        PARTITION p2025 VALUES LESS THAN (2026),
        PARTITION pMAX VALUES LESS THAN MAXVALUE
    );

